### ISSUE TITLE
Acronyms May need package Installation

### ISSUE THREAD

**Issue by jbae11** [arfc/pres#3]
In regards to #2 
With the acronym function and glossary generation,

If faced with error message:
`File tracklang.sty note found`

the user might have to 
`sudo apt-get install texlive-generic-extra`

in order for it to work properly.

**Comment by katyhuff** [comment]
Ah, now I *really* see what you were saying yesterday. P.S. Is the error message actually "File tracklang.sty note found" or is it "File tracklang.sty not found"? I assume it's the latter.

**Comment by katyhuff** [comment]
I'm not sure this is appropriate as an issue. It was solved before it was created. It maybe is more appropriate as a note in the readme, as helpful documentation for the user. Otherwise, this issue will remain open forever... because there's no way to solve it, because it's already solved.

**Comment by jbae11** [comment]
Yup! it's definitely the not found one sorry!
and the readme is updated!
thanks

**Comment by katyhuff** [comment]
Perfect!
