### ISSUE TITLE
Cyclus presentation

### ISSUE THREAD

**Issue by jbae11** [arfc/pres#5]
@FlanFlanagan @katyhuff
I have created a brief presentation for Cyclus to present to the personnel in ORNL.  Please let me know if you have any comments.

The files (including the pdf) are in the [cyclus_pres branch](https://github.com/arfc/pres/tree/cyclus_pres).

*I apologize for the poorly screen-shotted code snippets. I could not figure out, after hours, how to put lstlisting (or minted) inside a frame. I will continue working on it.

**Comment by katyhuff** [comment]
I recommend using the newsletter for information about accomplishments: https://github.com/cyclus/cyclus.github.com/pull/283

**Comment by katyhuff** [comment]
What's the status here. Has this already been presented?

**Comment by jbae11** [comment]
This has been presented at ORNL on August 8th.
